### ISSUE TITLE
Implementing a 2D Array

### ISSUE THREAD

**Issue by Dinki-Yaduwanshi** [Jatin-Shihora/DSA-Essentials#11]
## Submission Type
- Part of Data Structures Directory

## Problem Description
- Add matrices addition and subtraction code implemented in java under the name "Matrice_Add_Sub.java"

## Submission Directory
- Data_Structures => Array => 2-D Array

Language
- [x] Java

 
Kindly assign me this issue.
Thanks

**Comment by Jatin-Shihora** [comment]
Ok, all good. Now you can create a pull request with the added file.

**Comment by Dinki-Yaduwanshi** [comment]
Thank you!
