### ISSUE TITLE
Doubly Linked List implementation with various functions

### ISSUE THREAD

**Issue by developerHarshRaj** [Jatin-Shihora/DSA-Essentials#19]
## Problem Link
- https://github.com/Jatin-Shihora/DSA-Essentials/tree/main/Data_Structures/LinkedList

## Submission Type
- It will going to be the part of Data Structures --> Linked List directory. 

## Problem Description
- I have seen that there are code for single linked list but double linked list codes are missing which is one of the main topic in Data Structures. I want to add that. Also I will be adding various functions of using that linked list like inserting, deleting, reversing, etc. Please assign me this issue to do that.

## Submission Directory
- DataStructure => LinkedList => DoublyLinkedList.java

Language
- [x] Java
 
Kindly assign me this issue.
Thanks

**Comment by Jatin-Shihora** [comment]
I have assigned @developerHarshRaj this issue. Happy Coding!!

**Comment by Jatin-Shihora** [comment]
This issue is successfully resolved by @developerHarshRaj .
