### ISSUE TITLE
Stack Implementation using Linked List

### ISSUE THREAD

**Issue by developerHarshRaj** [Jatin-Shihora/DSA-Essentials#2]
## Problem Link
https://github.com/Jatin-Shihora/DSA-Essentials/tree/main/Data_Structures/Stack/Implementation

## Problem Description
- The problem is that a stack can also be implemented using Linked List. I have that approach with me and I want to contribute that in your repo.

## Submission Directory
- DataStructure => Stack/Implementation 
- // I will add a seperate code file named like StackUsingLL.java in the above mentioned directory.

Language
- [x] Java
 
Kindly assign me this issue.
Thanks

**Comment by Jatin-Shihora** [comment]
I have assigned you this issue @developerHarshRaj . Happy coding!!
