### ISSUE TITLE
Request to enhance "Nth_Ugly_Number.java" as pull request

### ISSUE THREAD

**Issue by DmitriyShum** [Jatin-Shihora/DSA-Essentials#21]
## Problem Link
- https://www.github.com/Jatin-Shihora/DSA-Essentials/blob/main/Algorithms/DP/nth_ugly_number/Nth_Ugly_Number.java

## Submission Type
- Algorithms

## Problem Description
- I am interested in enhancing the class "Nth_Ugly_Number.java" as well as fixes.

## Submission Directory
- DataStructure/Algorithms => DP => nth_ugly_number => Nth_Ugly_Number.java

Language
- [] C
- [] C++
- [x] Java
- [] Python
- [] JavaScript
- [] C#
- [] Kotlin
- [] Go
 
Kindly assign me this issue.
Thanks

~ DmitriyShum

**Comment by Jatin-Shihora** [comment]
What enhancements are you going to do?

**Comment by DmitriyShum** [comment]
@Jatin-Shihora Less spaces, direct import, organization, and more comments for easier understanding. As well as fixes such as the class name.

**Comment by DmitriyShum** [comment]
A lot of other classes in the repository have file name problems that will have trouble running.

**Comment by Jatin-Shihora** [comment]
> A lot of other classes in the repository have file name problems that will have trouble running.

yeah, you are right on this, when I was changing my systems those file names got messed up. So if you want to rectify those things you can create a new issue for this let's not mix up Nth_Ugly_Number ;)

**Comment by Jatin-Shihora** [comment]
> @Jatin-Shihora Less spaces, direct import, organization, and more comments for easier understanding. As well as fixes such as the class name.

Ok, I am assigning @DmitriyShum this issue. Happy Coding ^_^

**Comment by DmitriyShum** [comment]
I'm on it!

**Comment by DmitriyShum** [comment]
What do you mean "let's not mix up Nth_Ugly_Number?"

**Comment by Jatin-Shihora** [comment]
> What do you mean by "let's not mix up Nth_Ugly_Number?"

Ok, So what I mean is to create one more issue for fixing those messy names for classes, you can take it as an enhancement-type issue or you can also create multiple issues with rectification done according to the subdirectory.

**Comment by Jatin-Shihora** [comment]
You did a good job @DmitriyShum. So now closing this issue :)
