### ISSUE TITLE
Requesting  to fix StringPermute.java file name + organization

### ISSUE THREAD

**Issue by DmitriyShum** [Jatin-Shihora/DSA-Essentials#24]
## Problem Link
- https://github.com/Jatin-Shihora/DSA-Essentials/blob/main/Algorithms/Backtracking/StringPermute/StringPermute.java

## Submission Type
- Algorithms

## Problem Description
- The file name doesn't match the name in the repository.

## Submission Directory
- Algorithms => Backtracking => StringPermute => StringPermute.java

Language
- [] C
- [] C++
- [x] Java
- [] Python
- [] JavaScript
- [] C#
- [] Kotlin
- [] Go
 
Kindly assign me this issue.
Thanks

 ~ Dmitriy

**Comment by DmitriyShum** [comment]
Also if you don't mind explaining or uploading the "Permutations.java" class, that would be amazing! I would like to see the code fully at work.

**Comment by Jatin-Shihora** [comment]
@DmitriyShum I have assigned you this issue. Apart from this, Permutations.java class is simply the implementation of the approach given below : 
Given a word w = c1c2c3c4c5 (we shall write it as w{1,5})
-   To find all permutations of a word w{1,5}, fix
    the character at the leftmost index of w{1,5}, this character can be any character after
    the leftmost index). 
-   Now, after fixing index 1, find all possible permutations of w{2,5}
    (how? just the way we did for w{1,5}).
    (i.e., fix the character at index 2, and find all possible permutations of w{3,5})
-   Keep doing this until we reach w{5,5}. When we reach there, print it out.
